name: Test pipeline

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        test-os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.test-os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pipenv and packages
        run: |
          python -m pip install pipenv
          python -m pipenv shell
          pipenv install
      - name: Run
        run: pytest