name: Test pipeline

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        test-os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.test-os }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.8
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Run tests
        run: |
          pipenv install --dev
          pipenv run pytest
