name: Test pipeline

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        test-os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.test-os }}
    steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones

      - name: Test
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: pytest